blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
   
    path('' , blog_home  , name= 'blog_home'),
    path('tag/<str:tag_name>' , blog_home , name= 'tag'),
    path('<str:cat_name>/' , blog_home , name= 'category'),
    path('author/<str:author_username>' , blog_home , name= 'author'),
    
    path('<int:pk>' , blog_single , name= 'blog_single'),    
   
    path('search/', blog_search , name= 'search'),
    
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls') , name='blog'),
    path('content/', include('content.urls') , name='content'),
    path('accounts/' , include('accounts.urls') , name = 'accounts'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# from jalali_date import datetime2jalali, date2jalali
from django.contrib.auth.models import User
from django.urls import reverse
# from taggit.managers import TaggableManager


class Category(models.Model):
    
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
class Post(models.Model):
    
    image = models.ImageField(upload_to='blog/' , default='blog/default.jpg')
    author = models.ForeignKey(User , on_delete=models.SET_NULL , null=True) 
    title = models.CharField(max_length=255)
    content = models.TextField()
    # tags = TaggableManager()
    category =  models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    login_require = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    published_date =models.DateTimeField(null=True , default=0)
    created_date = models.DateTimeField(auto_now_add=True )
    updated_date = models.DateTimeField(auto_now=True )
    
    class Meta:
         ordering = ['status']
         verbose_name = 'My Post Blog'
         verbose_name_plural = 'پست ها'
              
    
    def __str__(self):
        return self.title
    
    def snippets(self):
        return self.content[:200] + '...'
    
    def get_absolute_url(self):
        return reverse ('blog:blog_single' , kwargs={'pid' : self.id})
    
         
class Comment(models.Model):
    
    post = models.ForeignKey(Post , on_delete=models.CASCADE , null=True)
    name = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=150)
    message = models.TextField()
    approveh = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=False , null=True)
    updated_date = models.DateTimeField(auto_now_add=False , null=True)
    
    
    def __str__(self):
        return self.name

    
    

blog/forms.py
from django import forms
from blog.models import Post , Comment
# from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm): 
    class Meta:    
        model = Comment
        fields = ['post','name' , 'email' , 'subject' , 'message']
        

blog/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from .models import Post , Comment , Category
from django.core.paginator import Paginator , EmptyPage , PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Count

 
def blog_home (request , **kwargs):    
    posts = Post.objects.filter(status = 1)
    categories = categories = (
        Category.objects.annotate(num_posts=Count('post'))
        .filter(num_posts__gt=0)  
        .order_by('-num_posts')[:4]  
    )
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs ['cat_name'])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username = kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in= [kwargs['tag_name']])
    posts = Paginator(posts , 3)
    try:
        
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
        
    except PageNotAnInteger: 
        posts = posts.get_page(1)    
    except EmptyPage: 
        posts = posts.get_page(1)    
    context = {'posts' : posts , 'categories' : categories}
    return render (request , 'blog/blog_home.html' , context)
 


def blog_single(request , pk):

    if request.method == 'POST' :
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request , messages.SUCCESS,' Comment Done')       
        else:
            messages.add_message(request , messages.ERROR,' Your Comment didnt submiter ')
            
    post = Post.objects.get(id = pk , status = 1 )
    categories = Category.objects.annotate(num_posts=Count('post'))
    if not post.login_require:
                comments = Comment.objects.filter(post=post.id , approveh=True)
                posts = get_object_or_404(Post,id=pk) 
                form = CommentForm()
                context = {'posts' : posts , 'comments':comments , 'form':form , 'categories' : categories}
                return render (request , 'blog/blog-single.html' , context)
    else:
        if request.user.is_authenticated:
                comments = Comment.objects.filter(post=post.id , approveh=True)
                posts = get_object_or_404(Post,id=pk)
                form = CommentForm()
                context = {'posts' : posts , 'comments':comments , 'form':form , 'categories' : categories}
                return render (request , 'blog/blog-single.html' , context)
        else:
                return HttpResponseRedirect(reverse('accounts:login'))

def blog_category(request , cat_name):
    posts = Post.objects.filter(status = 1)
    posts = posts.filter(category__name=cat_name)
    context = {'posts' : posts}
    return render (request , 'blog/blog-home.html' , context)

def blog_search(request):
    posts = Post.objects.filter(status = 1)  
    
    if request.method == "GET":
        if s :=  request.GET.get('s'):       
            posts = posts.filter(content__contains = s ) 
    context = {'posts' : posts}
    return render (request , 'blog/blog-home.html' , context)

templates/blog/blog-single.html
{% extends "base.html" %}
{% load static %}
{% block content %}  

  
  <!--================ Hero sm Banner start =================-->      
  <section class="mb-30px">
    <div class="container">
      <div class="hero-banner hero-banner--sm">
        <div class="hero-banner__content">
          <h1>{{ posts.title }}</h1>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url "blog:blog_home" %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--================ Hero sm Banner end =================-->    

  <!--================ Start Blog Post Area =================-->
  <section class="blog-post-area section-margin">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
            <div class="main_blog_details">
                <img class="img-fluid" src="{{ posts.image.url }}" alt="">
                <a href="#"><h4>{{ posts.title }}</h4></a>
                <div class="user_details">
                  <div class="float-left">
                    
                    <a href="#">Lifestyle</a>
                    <a href="#">Gadget</a>
                  </div>
                  <div class="float-right mt-sm-0 mt-3">
                    <div class="media">
                      <div class="media-body">
                        <h5>{{ posts.author.get_full_name }}</h5>
                        <p>1{{ posts.published_date| date:"M - Y" }}</p>
                      </div>
                      <div class="d-flex">
                        <img width="42" height="42" src="{% static "img/blog/user-img.png" %}" alt="">
                      </div>
                    </div>
                  </div>
                </div>
                <p> {{ posts.content }} </p> 
               <div class="news_d_footer flex-column flex-sm-row">
                 <a href="#"><span class="align-middle mr-2"><i class="ti-heart"></i></span>{{ post.counted_views}}</a>
                 <a class="justify-content-sm-center ml-sm-auto mt-sm-0 mt-2" href="#"><span class="align-middle mr-2"><i class="ti-themify-favicon"></i></span>06 Comments</a>
                 <div class="news_socail ml-sm-auto mt-sm-0 mt-2">
               <a href="#"><i class="fab fa-facebook-f"></i></a>
               <a href="#"><i class="fab fa-twitter"></i></a>
               <a href="#"><i class="fab fa-dribbble"></i></a>
               <a href="#"><i class="fab fa-behance"></i></a>
             </div>
               </div>
              </div>
          

          <div class="navigation-area">
                  <div class="row">
                      <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                          <div class="thumb">
                              <a href="#"><img class="img-fluid" src="{% static "img/blog/prev.jpg" %}" alt=""></a>
                          </div>
                          <div class="arrow">
                              <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                          </div>
                          <div class="detials">
                              <p>Prev Post</p>
                              <a href="#"><h4>A Discount Toner</h4></a>
                          </div>
                      </div>
                      <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                          <div class="detials">
                              <p>Next Post</p>
                              <a href="#"><h4>Cartridge Is Better</h4></a>
                          </div>
                          <div class="arrow">
                              <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                          </div>
                          <div class="thumb">
                              <a href="#"><img class="img-fluid" src="{% static "img/blog/next.jpg" %}" alt=""></a>
                          </div>										
                      </div>									
                  </div>
                </div>
                <div class="comments-area">
                    <h4>05 Comments</h4>
                    <div class="comment-list">
                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">
                                <div class="thumb">
                                    <img src="{% static "img/blog/c1.jpg" %}" alt="">
                                </div>
                                <div class="desc">
                                    <h5><a href="#">Emilly Blunt</a></h5>
                                    <p class="date">December 4, 2017 at 3:12 pm </p>
                                    <p class="comment">
                                        Never say goodbye till the end comes!
                                    </p>
                                </div>
                            </div>
                            <div class="reply-btn">
                                    <a href="" class="btn-reply text-uppercase">reply</a> 
                            </div>
                        </div>
                    </div>	
                    <div class="comment-list left-padding">
                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">
                                <div class="thumb">
                                    <img src="{% static "img/blog/c2.jpg" %}" alt="">
                                </div>
                                <div class="desc">
                                    <h5><a href="#">Elsie Cunningham</a></h5>
                                    <p class="date">December 4, 2017 at 3:12 pm </p>
                                    <p class="comment">
                                        Never say goodbye till the end comes!
                                    </p>
                                </div>
                            </div>
                            <div class="reply-btn">
                                    <a href="" class="btn-reply text-uppercase">reply</a> 
                            </div>
                        </div>
                    </div>		                                             				
                </div>
                <div class="comment-form">
                    <h4>Leave a Reply</h4>
                    <form>
                        <div class="form-group form-inline">
                          <div class="form-group col-lg-6 col-md-6 name">
                            <input type="text" class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
                          </div>
                          <div class="form-group col-lg-6 col-md-6 email">
                            <input type="email" class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
                          </div>										
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
                        </div>
                        <a href="#" class="button submit_btn">Post Comment</a>	
                    </form>
                </div>
        </div>

        <!-- Start Blog Post Siddebar -->
        <div class="col-lg-4 sidebar-widgets">
            <div class="widget-wrap">
              <div class="single-sidebar-widget newsletter-widget">
                <h4 class="single-sidebar-widget__title">Newsletter</h4>
                <div class="form-group mt-30">
                  <div class="col-autos">
                    <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''"
                      onblur="this.placeholder = 'Enter email'">
                  </div>
                </div>
                <button class="bbtns d-block mt-20 w-100">Subcribe</button>
              </div>


              <div class="single-sidebar-widget post-category-widget">
                <h4 class="single-sidebar-widget__title">Catgory</h4>
                <ul class="cat-list mt-20">
                  
                    {% for cat in posts.category.all %}
                      <li>
                        <a href="{% url "blog:category" cat_name=cat.name %}" class="d-flex justify-content-between">
                          <p>{{ cat.name }}</p> 
                          <p>{{ cat.name_set.count }}</p>
                        </a>
                      </li>
                    {% endfor %}    
                  

                </ul>
              </div>

              <div class="single-sidebar-widget popular-post-widget">
                <h4 class="single-sidebar-widget__title">Popular Post</h4>
                <div class="popular-post-list">
                  <div class="single-post-list">
                    <div class="thumb">
                      <img class="card-img rounded-0" src="{% static "img/blog/thumb/thumb1.png" %}" alt="">
                      <ul class="thumb-info">
                        <li><a href="#">Adam Colinge</a></li>
                        <li><a href="#">Dec 15</a></li>
                      </ul>
                    </div>
                    <div class="details mt-20">
                      <a href="blog-single.html">
                        <h6>Accused of assaulting flight attendant miktake alaways</h6>
                      </a>
                    </div>
                  </div>
                </div>
              </div>

                <div class="single-sidebar-widget tag_cloud_widget">
                  <h4 class="single-sidebar-widget__title">Popular Post</h4>
                  <ul class="list">
                    <li>
                        <a href="#">project</a>
                    </li>
                    <li>
                        <a href="#">love</a>
                    </li>
                    <li>
                        <a href="#">technology</a>
                    </li>
                    <li>
                        <a href="#">travel</a>
                    </li>
                    <li>
                        <a href="#">software</a>
                    </li>
                    <li>
                        <a href="#">life style</a>
                    </li>
                    <li>
                        <a href="#">design</a>
                    </li>
                    <li>
                        <a href="#">illustration</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <!-- End Blog Post Siddebar -->
      </div>
  </section>
  <!--================ End Blog Post Area =================-->

  

{% endblock content %}

templates/blog/blog_home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  
  <main class="site-main">
    <!--================Hero Banner start =================-->  
    <section class="mb-30px">
      <div class="container">
        <div class="hero-banner">
          <div class="hero-banner__content">
            <h3>Tours & Travels</h3>
            <h1>Amazing Places on earth</h1>
            <h4>December 12, 2018</h4>
          </div>
        </div>
      </div>
    </section>
    <!--================Hero Banner end =================-->  

    <!--================ Blog slider start =================-->  
    <section>
      <div class="container">
        <div class="owl-carousel owl-theme blog-slider">
          <div class="card blog__slide text-center">
            <div class="blog__slide__img">
              <img class="card-img rounded-0" src="{% static "img/blog/blog-slider/blog-slide1.png" %}" alt="">
            </div>
            <div class="blog__slide__content">
              <a class="blog__slide__label" href="#">Fashion</a>
              <h3><a href="#">New york fashion week's continued the evolution</a></h3>
              <p>2 days ago</p>
            </div>
          </div>
          <div class="card blog__slide text-center">
            <div class="blog__slide__img">
              <img class="card-img rounded-0" src="{% static "img/blog/blog-slider/blog-slide2.png" %}" alt="">
            </div>
            <div class="blog__slide__content">
              <a class="blog__slide__label" href="#">Fashion</a>
              <h3><a href="#">New york fashion week's continued the evolution</a></h3>
              <p>2 days ago</p>
            </div>
          </div>
          <div class="card blog__slide text-center">
            <div class="blog__slide__img">
              <img class="card-img rounded-0" src="{% static "img/blog/blog-slider/blog-slide3.png" %}" alt="">
            </div>
            <div class="blog__slide__content">
              <a class="blog__slide__label" href="#">Fashion</a>
              <h3><a href="#">New york fashion week's continued the evolution</a></h3>
              <p>2 days ago</p>
            </div>
          </div>
          <div class="card blog__slide text-center">
            <div class="blog__slide__img">
              <img class="card-img rounded-0" src="{% static "img/blog/blog-slider/blog-slide1.png" %}" alt="">
            </div>
            <div class="blog__slide__content">
              <a class="blog__slide__label" href="#">Fashion</a>
              <h3><a href="#">New york fashion week's continued the evolution</a></h3>
              <p>2 days ago</p>
            </div>
          </div>
          <div class="card blog__slide text-center">
            <div class="blog__slide__img">
              <img class="card-img rounded-0" src="{% static "img/blog/blog-slider/blog-slide2.png" %}" alt="">
            </div>
            <div class="blog__slide__content">
              <a class="blog__slide__label" href="#">Fashion</a>
              <h3><a href="#">New york fashion week's continued the evolution</a></h3>
              <p>2 days ago</p>
            </div>
          </div>
          <div class="card blog__slide text-center">
            <div class="blog__slide__img">
              <img class="card-img rounded-0" src="{% static "img/blog/blog-slider/blog-slide3.png" %}" alt="">
            </div>
            <div class="blog__slide__content">
              <a class="blog__slide__label" href="#">Fashion</a>
              <h3><a href="#">New york fashion week's continued the evolution</a></h3>
              <p>2 days ago</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ Blog slider end =================-->  

    <!--================ Start Blog Post Area =================-->
    <section class="blog-post-area section-margin mt-4">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            {% for posts in posts %}
              <div class="single-recent-blog-post">
                <div class="thumb">
                  <img class="img-fluid" src="{{ posts.image.url }}" alt="">
                  <ul class="thumb-info">
                    <li><a href="{% url "blog:author" author_username=posts.author.username %}"><i class="ti-user"></i>{{ posts.author.get_full_name }}</a></li>
                    <li><a href="#"><i class="ti-notepad"></i>{{ posts.published_date|date:"M - Y" }}</a></li>
                    <li><a href="#"><i class="ti-themify-favicon"></i>{{ posts.counted_views }}</a></li>
                  </ul>
                </div>
                <div class="details mt-20">
                  <a href="blog-single.html">
                    <h3>{{ posts.title }}.</h3>
                  </a>
                  
                    <p class="tag-list-inline">Catgory:{% for cat in posts.category.all %}  <a href="{% url "blog:category" cat_name=cat.name %}">{{cat.name}}</a> {% if not forloop.last %},{% endif %} {% endfor %}</p>
                   
                  <p>{{ posts.snippets}}</p>
                  <p class="tag-list-inline">Tag: <a href="#">travel</a>, <a href="#">life style</a>, <a href="#">technology</a>, <a href="#">fashion</a></p>
                  <a class="button" href="{% url "blog:blog_single" pk=posts.id %}">Read More <i class="ti-arrow-right"></i></a>
                </div>
              </div>
            {% endfor %}
          
            <div class="row">
              <div class="col-lg-12">
                  <nav class="blog-pagination justify-content-center d-flex">
                      <ul class="pagination">
                          <li class="page-item">
                            {% if posts.has_previous %} 
                                  <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                                      <span aria-hidden="true">
                                          <i class="ti-angle-left"></i>
                                      </span>
                                  </a>
                              </li>
                            {% endif %}
                            {% for i in posts.paginator.page_range %}
                            {% if posts.number == i %}
                          <li class="page-item active"><a href="?page={{i}}" class="page-link">{{ i }}</a></li>
                          {% else %}
                          <li class="page-item"><a href="?page={{i}}" class="page-link">{{ i }}</a></li>
                          {% endif %}
                          {% endfor %}
                          {% if posts.has_next %}
                            <li class="page-item">
                                <a href="?page={{ posts.paginator.num_pages }}" class="page-link" aria-label="Next">
                                    <span aria-hidden="true">
                                        <i class="ti-angle-right"></i>
                                    </span>
                                </a>
                            </li>
                          {% endif %}
                      </ul>
                  </nav>
              </div>
            </div>
          </div>

          <!-- Start Blog Post Siddebar -->
          <div class="col-lg-4 sidebar-widgets">
              <div class="widget-wrap">
                <div class="single-sidebar-widget newsletter-widget">
                  <h4 class="single-sidebar-widget__title">Newsletter</h4>
                  <div class="form-group mt-30">
                    <div class="col-autos">
                      <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''"
                        onblur="this.placeholder = 'Enter email'">
                    </div>
                  </div>
                  <button class="bbtns d-block mt-20 w-100">Subcribe</button>
                </div>
                  {% include "category.html" %}

                <div class="single-sidebar-widget popular-post-widget">
                  <h4 class="single-sidebar-widget__title">Popular Post</h4>
                  <div class="popular-post-list">
                    <div class="single-post-list">
                      <div class="thumb">
                        <img class="card-img rounded-0" src="{% static "img/blog/thumb/thumb1.png" %}" alt="">
                        <ul class="thumb-info">
                          <li><a href="#">Adam Colinge</a></li>
                          <li><a href="#">Dec 15</a></li>
                        </ul>
                      </div>
                      <div class="details mt-20">
                        <a href="blog-single.html">
                          <h6>Accused of assaulting flight attendant miktake alaways</h6>
                        </a>
                      </div>
                    </div>
                    <div class="single-post-list">
                      <div class="thumb">
                        <img class="card-img rounded-0" src="{% static "img/blog/thumb/thumb2.png" %}" alt="">
                        <ul class="thumb-info">
                          <li><a href="#">Adam Colinge</a></li>
                          <li><a href="#">Dec 15</a></li>
                        </ul>
                      </div>
                      <div class="details mt-20">
                        <a href="blog-single.html">
                          <h6>Tennessee outback steakhouse the
                            worker diagnosed</h6>
                        </a>
                      </div>
                    </div>
                    <div class="single-post-list">
                      <div class="thumb">
                        <img class="card-img rounded-0" src="{% static "img/blog/thumb/thumb3.png" %}" alt="">
                        <ul class="thumb-info">
                          <li><a href="#">Adam Colinge</a></li>
                          <li><a href="#">Dec 15</a></li>
                        </ul>
                      </div>
                      <div class="details mt-20">
                        <a href="blog-single.html">
                          <h6>Tennessee outback steakhouse the
                            worker diagnosed</h6>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>

                  <div class="single-sidebar-widget tag_cloud_widget">
                    <h4 class="single-sidebar-widget__title">Popular Post</h4>
                    <ul class="list">
                      <li>
                          <a href="#">project</a>
                      </li>
                      <li>
                          <a href="#">love</a>
                      </li>
                      <li>
                          <a href="#">technology</a>
                      </li>
                      <li>
                          <a href="#">travel</a>
                      </li>
                      <li>
                          <a href="#">software</a>
                      </li>
                      <li>
                          <a href="#">life style</a>
                      </li>
                      <li>
                          <a href="#">design</a>
                      </li>
                      <li>
                          <a href="#">illustration</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          <!-- End Blog Post Siddebar -->
        </div>
    </section>
    <!--================ End Blog Post Area =================-->
  </main>
  
{% endblock content %}
 